In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np; np.random.seed(0)
from extquadcontrol import dp_infinite, ExtendedQuadratic
import matplotlib.pyplot as plt
from plot_settings import savefig

# Birdwell example

In [3]:
n = 2
m = 2
K = 3
T = 30
N = 1

Amean = np.diag([2.71828,0.36788]).reshape(1,1,n,n)
Bmean = np.array([[1.71828,1.71828],[-0.63212,0.63212]])
actuator_configurations = [[],[0],[1]]

Pi = np.eye(K)+np.random.uniform(0,.1,size=(K,K))
Pi /= np.sum(Pi,axis=0)

In [4]:
np.set_printoptions(precision=3)
Pi = np.array([[0.898, 0.075, 0.014],
       [0.02 , 0.898, 0.036],
       [0.081, 0.028, 0.95 ]])

In [5]:
def sample(N):
    A = np.zeros((N,K,n,n)); A[:] = Amean
    B = np.zeros((N,K,n,m)); B[:] = Bmean
    for i in range(K):
        failures = actuator_configurations[i]
        B[:,i,:,failures] = 0
    c = np.zeros((N,K,n))
    g = [[ExtendedQuadratic(np.eye(n+m),np.zeros(n+m),0) for _ in range(K)] for _ in range(N)]
    
    return A,B,c,g,Pi

Vs, Qs, policies = dp_infinite(sample, T, N)

In [6]:
A, B, c, g, Pi = sample(1)

In [7]:
policies[0]

(array([[-0.737,  0.135],
        [-0.74 , -0.136]]), array([0., 0.]))

In [8]:
policies[1]

(array([[ 0.   ,  0.   ],
        [-1.455, -0.003]]), array([0., 0.]))

In [9]:
policies[2]

(array([[-1.462,  0.002],
        [ 0.   ,  0.   ]]), array([0., 0.]))